# Generated by Django 4.1 on 2022-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sisul',
            name='safety',
        ),
        migrations.AlterField(
            model_name='sisul',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
